### ISSUE TITLE
Partial bundle vs. Freeze Attack vs. Mix-and-match

### ISSUE THREAD

**Issue by JosiahOne** [uptane/uptane-standard#18]
In the section 4.3 ("Description of threats") three attacks are presented (as well as others):

1. "Freeze attack": Continue to send a previously known update to an ECU, even if a newer update exists.
2. "Partial bundle installation attack": Install updates to some ECUs, but freeze updates on others.
3. "Mix-and-match attack": Install a set of images on ECUs in the vehicle that are incompatible with each other...

I read through 1 and 2 without issue, but when I read 3, I became slightly confused. I didn't immediately see how 3 ("Mix-and-match") is any different than 2 ("Partial bundle installation attack"). I ended up convincing myself that they are more or less the same, but have different names because the "type" of attack was different.

But given that, I then questioned whether there is really a distinction between a "freeze attack" and a "partial bundle installation attack." It seems a "partial bundle installation attack" is just a "freeze attack on a subset of the ECUs", so why give it its own name?

After re-reviewing the uptane design overview document, I determined that, in fact, all three are quite different.

1. A freeze attack refers to sending an old (but properly signed) update BUNDLE.
2. A partial bundle attack refers to a valid (signed) BUNDLE being installed, but where you selectively block certain 'sub updates' parts.
3. A mix and match attack requires an attacker to provide a malicious BUNDLE, where some of the 'sub-updates' don't interoperate properly.

I think the standard should be clarified to prevent this confusion. In my opinion the root cause is that we don't discuss "bundles" at all in this part of the standard.

**Comment by jhdalek55** [comment]
First off, this is good work...it represents the type of close reading we could use at this point in the standard's development.
What would be your suggestion for resolving this problem? It seems we need to define "bundles" somewhere. Would a definition in Section 2 be enough, or should we add a brief definition/description in this section as part of the explanation of this group of attacks?

**Comment by JosiahOne** [comment]
I think defining the term in section 2, and then referencing it (similar to my last enumerated list) would probably be adequate.

**Comment by OYTIS** [comment]
+1 for defining bundles. It would bring the standard closer to how updates are done today.

**Comment by jhdalek55** [comment]
I am planning to do a "proofing run" on the document today. I've been making some notes of some minor wording issues throughout the document on a hard copy and can address these comments, as well. I appreciate Josiah pointing to this missing term. It's the kind of close reading we could really use at this point.

Given the problems I have had with formatting in the past I will leave the PR for review. I don't plan on changing anything but the wording, as per above. It will not require a technical review, just an assurance that there are no formatting issues.

I hope to get that done in a few hours.

Lois

**Comment by JosiahOne** [comment]
Hey @jhdalek55 ,

Have you already done that "proofing run" you mentioned above? If not, would it be helpful if I created a PR with a fix for this issue?

**Comment by jhdalek55** [comment]
To be honest, Josiah, I've done the proofing, but haven't committed 
anything to github. My initial batch of changes a few months ago created 
formatting issues, and though the have long since been corrected, I have 
been a bit leary about re-using my forked copy and haven't figured out a 
way to get my corrections in yet. So, yes, why don't you go ahead and 
fix what needs correcting on that branch. The other changes I was going 
to make are not as significant as the clarification you proposed.


I apologize for not keeping you aware of progress on this issue.


Lois



On Fri, Dec 07, 2018 at 01:59 PM, Josiah Bruner (:JosiahOne) wrote:

Hey @jhdalek55 
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_jhdalek55&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hgBKIqNYIOwzXeBjPUaKRw&m=202PV_5NB3TpQCv4RaSC_gBDuFh6f-JhYp2foBUZfAY&s=25NokgWXPBenfHEfmaIAMqG4AVakare-BbUP7CWoF8M&e=> 
,

Have you already done that "proofing run" you mentioned above? If not, 
would it be helpful if I created a PR with a fix for this issue?


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub 
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_uptane_uptane-2Dstandard_issues_18-23issuecomment-2D445331496&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hgBKIqNYIOwzXeBjPUaKRw&m=202PV_5NB3TpQCv4RaSC_gBDuFh6f-JhYp2foBUZfAY&s=GErDH8jqZ4Arfe2F1dHPxjN8WHgU3q_s7-mpFg0asg4&e=> 
, or mute the thread 
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AN5qX3YWNkiq-5FtxkPq4r0-5FnsiOpxhXxuks5u2rqigaJpZM4Y2ai8&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hgBKIqNYIOwzXeBjPUaKRw&m=202PV_5NB3TpQCv4RaSC_gBDuFh6f-JhYp2foBUZfAY&s=Y56kH92ZYH1prfI3jmzlgaXNvwGQa2VFHtYtmUyMQjU&e=> 
.

**Comment by jhdalek55** [comment]
I posted the pull request. Let me know if what I came up with is sufficient or do we need a bit more explanation about bundles.

**Comment by JosiahOne** [comment]
This was resolved in #24
