### ISSUE TITLE
Secondaries without secondary storage

### ISSUE THREAD

**Issue by pattivacek** [uptane/uptane-standard#186]
In [section 5.4.2.6](https://uptane.github.io/uptane-standard/uptane-standard.html#rfc.section.5.4.2.6), we say, "Each Secondary SHALL store the latest copy of all metadata required for its own verification." In [the following section](https://uptane.github.io/uptane-standard/uptane-standard.html#rfc.section.5.4.2.7), we then say, "For Secondaries without storage [...]". Other sections also refer to Secondaries without secondary storage.

How should a Secondary without secondary storage "store the latest copy of all metadata required for its own verification"?

And could we find a better phrase for "secondary storage"? It's confusing when we are talking about Secondaries.

**Comment by iramcdonald** [comment]
Hi Patrick,

A couple of intertwined thoughts here:

(1) Change "secondary storage" to "protected storage" (a term being used
across specs
in TCG, SAE, Global Platform, and other SDOs to emphasize that the relevant
metadata,
keys, etc., are useless if they are not *reliably* stored).

(2) I have never liked the idea that an Uptane Secondary could exist with
some minimum
amount of computational resources and protected storage - because such an
ECU is a
security hole in the Uptane security guarantees.

The second thought is a philosophical and implementation topic that really
needs to be
nailed down and resolved by Uptane v2.0.0 (if not sooner).

Cheers,
- Ira


*Ira McDonald (Musician / Software Architect)*

*Chair - SAE Trust Anchors and Authentication TF*
*Co-Chair - TCG Trusted Mobility Solutions WG*

*Co-Chair - TCG Metadata Access Protocol SG*








*Chair - Linux Foundation Open Printing WGSecretary - IEEE-ISTO Printer
Working GroupCo-Chair - IEEE-ISTO PWG Internet Printing Protocol WGIETF
Designated Expert - IPP & Printer MIBBlue Roof Music / High North
Inchttp://sites.google.com/site/blueroofmusic
<http://sites.google.com/site/blueroofmusic>http://sites.google.com/site/highnorthinc
<http://sites.google.com/site/highnorthinc>mailto: blueroofmusic@gmail.com
<blueroofmusic@gmail.com>(permanent) PO Box 221  Grand Marais, MI 49839
906-494-2434*

**Comment by patrickvacek** [comment]
> (1) Change "secondary storage" to "protected storage" (a term being used across specs in TCG, SAE, Global Platform, and other SDOs to emphasize that the relevant metadata, keys, etc., are useless if they are not *reliably* stored).

Interesting, I haven't heard that term before. An internet search mostly returns some proprietary Windows tool. I think this might require a bit more discussion before I make any changes.

> (2) I have never liked the idea that an Uptane Secondary could exist with some minimum amount of computational resources and protected storage - because such an ECU is a security hole in the Uptane security guarantees.

What do you mean? I think there's either a typo or I'm missing something obvious... how else would you have your Secondaries?

**Comment by iramcdonald** [comment]
Hi Patrick,

Sorry - up all night w/ IETF 109 Virtual Conference sessions.

On item (2) I meant "without minimum computing resources and protected
storage", because in that case it's not a legitimate Secondary, IMO.

Cheers,
- Ira

*Ira McDonald (Musician / Software Architect)*

*Chair - SAE Trust Anchors and Authentication TF*
*Co-Chair - TCG Trusted Mobility Solutions WG*

*Co-Chair - TCG Metadata Access Protocol SG*








*Chair - Linux Foundation Open Printing WGSecretary - IEEE-ISTO Printer
Working GroupCo-Chair - IEEE-ISTO PWG Internet Printing Protocol WGIETF
Designated Expert - IPP & Printer MIBBlue Roof Music / High North
Inchttp://sites.google.com/site/blueroofmusic
<http://sites.google.com/site/blueroofmusic>http://sites.google.com/site/highnorthinc
<http://sites.google.com/site/highnorthinc>mailto: blueroofmusic@gmail.com
<blueroofmusic@gmail.com>(permanent) PO Box 221  Grand Marais, MI 49839
906-494-2434*

**Comment by patrickvacek** [comment]
> On item (2) I meant "without minimum computing resources and protected storage", because in that case it's not a legitimate Secondary, IMO.

Got it. Yes, I think we share the same concern: if you can't even store Targets metadata, then how can you check versions for rollback attacks? Maybe we need to rethink how we phrase this in the Standard.

**Comment by iramcdonald** [comment]
Hi Patrick,

Somewhat in jest... What about an Uptane Tertiary?  A really
resource-constrained
Secondary who "trusts" the Uptane Primary (via in-vehicle authentication
methods)
and (implicitly) the Uptane Director (via transport protocol endpoint
authentication)
to only forward valid firmware updates (e.g., via UDS diagnostic
interfaces).

In practice, that means there need to be in-vehicle entities like:
(a) Telematics ECUs (w/ firewalls);
(b) Security Gateway ECUs (w/ intrusion detection scanning); and
(c) probably Domain Controller ECUs (on each subnet of the in-vehicle
network).
To isolate the Uptane Tertiary from bad guys on the public Internet.

My vision for Uptane v2.0.0 includes:

(a) More text about "trustworthiness", various methods (PKI and non-PKI) of
creating
hardware "trust anchors", and methods of creating "chains of trust" for
resources;

(b) New text about strong ECU identity (especially IEEE 802.1AR Device ID)
that is
more secure than supplier-name-prefixed serial numbers.

(c) New text about strong software identity (especially IETF CoSWID tags)
that is
more secure than current supplier/OEM proprietary software version info.

(d) New text that references SAE J3101 (H/W Protected Security
Environments, aka
HSMs), ISO/SAE 21434 Vehicle Cybersecurity, ISO 24089 Vehicle S/W Update,
and
a few others.  These will be the core specs for security audits for UNECE
WP29
regulations in the very near future (2022).

Cheers,
- Ira

*Ira McDonald (Musician / Software Architect)*

*Chair - SAE Trust Anchors and Authentication TF*
*Co-Chair - TCG Trusted Mobility Solutions WG*

*Co-Chair - TCG Metadata Access Protocol SG*








*Chair - Linux Foundation Open Printing WGSecretary - IEEE-ISTO Printer
Working GroupCo-Chair - IEEE-ISTO PWG Internet Printing Protocol WGIETF
Designated Expert - IPP & Printer MIBBlue Roof Music / High North
Inchttp://sites.google.com/site/blueroofmusic
<http://sites.google.com/site/blueroofmusic>http://sites.google.com/site/highnorthinc
<http://sites.google.com/site/highnorthinc>mailto: blueroofmusic@gmail.com
<blueroofmusic@gmail.com>(permanent) PO Box 221  Grand Marais, MI 49839
906-494-2434*

**Comment by patrickvacek** [comment]
> What about an Uptane Tertiary? A really resource-constrained Secondary who "trusts" the Uptane Primary (via in-vehicle authentication methods) and (implicitly) the Uptane Director (via transport protocol endpoint authentication) to only forward valid firmware updates (e.g., via UDS diagnostic interfaces).

To me, this sounds like what we've been calling a "legacy Secondary", i.e., an ECU that doesn't implement any Uptane verification and generally gets flashed by an installation manager based on the Primary's metadata verification. In practice, that's where most Secondaries in the field are still at.

**Comment by jhdalek55** [comment]
@patrickvacek ...so should this be flagged for 2.0.0?

**Comment by iramcdonald** [comment]
Hi Patrick,

I understand what you mean.  But I'm *strongly* opposed to using the
term "legacy Secondary" into the Uptane Standard or Deployment Best
Practices.  We don't have to use "Tertiary" (my humor), but we *really*
SHOULD NOT overload the term "Secondary" with that "legacy" hand
waving.

Lois - all of that stuff in my previous note about future content in Uptane
v2.0.0 of course belongs elsewhere, not just buried in this issue thread.

Cheers,
- Ira

*Ira McDonald (Musician / Software Architect)*

*Chair - SAE Trust Anchors and Authentication TF*
*Co-Chair - TCG Trusted Mobility Solutions WG*

*Co-Chair - TCG Metadata Access Protocol SG*








*Chair - Linux Foundation Open Printing WGSecretary - IEEE-ISTO Printer
Working GroupCo-Chair - IEEE-ISTO PWG Internet Printing Protocol WGIETF
Designated Expert - IPP & Printer MIBBlue Roof Music / High North
Inchttp://sites.google.com/site/blueroofmusic
<http://sites.google.com/site/blueroofmusic>http://sites.google.com/site/highnorthinc
<http://sites.google.com/site/highnorthinc>mailto: blueroofmusic@gmail.com
<blueroofmusic@gmail.com>(permanent) PO Box 221  Grand Marais, MI 49839
906-494-2434*

**Comment by jhdalek55** [comment]
@iramcdonald. With your permission, I was going to take that "wish list" for 2.0.0 and throw it in the agenda for our Tuesday meeting. One of the two agenda items I mentioned was reviewing what's already on our 2.0.0. list. I'd like to throw these things into the mix as well.

**Comment by iramcdonald** [comment]
Hi Lois,

Permission granted.

Since the various key SAE, ISO, and IETF specs are either published or
going to be
published in 2021, I was thinking it was time to give some "teeth" to some
Uptane
Standard requirements and/or Deployment recommendations.

Cheers,
- Ira

*Ira McDonald (Musician / Software Architect)*

*Chair - SAE Trust Anchors and Authentication TF*
*Co-Chair - TCG Trusted Mobility Solutions WG*

*Co-Chair - TCG Metadata Access Protocol SG*








*Chair - Linux Foundation Open Printing WGSecretary - IEEE-ISTO Printer
Working GroupCo-Chair - IEEE-ISTO PWG Internet Printing Protocol WGIETF
Designated Expert - IPP & Printer MIBBlue Roof Music / High North
Inchttp://sites.google.com/site/blueroofmusic
<http://sites.google.com/site/blueroofmusic>http://sites.google.com/site/highnorthinc
<http://sites.google.com/site/highnorthinc>mailto: blueroofmusic@gmail.com
<blueroofmusic@gmail.com>(permanent) PO Box 221  Grand Marais, MI 49839
906-494-2434*

**Comment by jhdalek55** [comment]
Thanks, Ira. Please make sure the comments stay here till I can move them.

**Comment by patrickvacek** [comment]
> I understand what you mean. But I'm *strongly* opposed to using the term "legacy Secondary" into the Uptane Standard or Deployment Best Practices. We don't have to use "Tertiary" (my humor), but we *really* SHOULD NOT overload the term "Secondary" with that "legacy" hand waving.

Ira, I hear that concern. I agree that "legacy Secondary" is a really ambiguous term and we should avoid it. The problem is the phrase we use now "Secondary without secondary storage" is not much better. I think these are actually addressing two separate categories, both of which need better names. Here is the way I've always broken down types of Secondaries from the Uptane perspective:

1. Secondaries powerful enough to do full verification.
2. Resource-constrained Secondaries that have just enough storage and power to perform partial verification.
3. Very low-power Secondaries that cannot do any verification themselves.

Category 3 is generally outside the scope of Uptane, but we still need to have a term to discuss them. (It may be worth mentioning somewhere that you *can* still update them in an Uptane system, but you get none of the protections that come from Secondary verification and that is at best a half-baked or transitional state of affairs from the Uptane perspective.)

Once someone understands Uptane, we can just use terms like "full verification Secondary", "partial verification Secondary", and "non-Uptane Secondary", but I think we have to explain that in slightly more detail at least once.

And regardless of terminology, we still need to explain how a "Secondary without secondary storage" should "store the latest copy of all metadata required for its own verification".

FYI I don't expect this to be resolved by our 1.1.0 deadline, and it's fine with me if we take our time getting this right.

**Comment by iramcdonald** [comment]
Hi Patrick,

But "non-Uptane Secondary" is inherently ambiguous, because it's still
overloading "Secondary".

We need to avoid the ambiguity of "non-Uptane (or whatever) Secondary"
to mean something that is not a titlecased "Secondary" at all.

No validation is the Wild West.  Unless we come up with a proper term and
define it as something like "an ECU that trusts an upstream component
(e.g., an Uptane Primary) to perform all necessary validation and to only
forward valid firmware (e.g., via UDS commands)".

Cheers,
- Ira


*Ira McDonald (Musician / Software Architect)*

*Chair - SAE Trust Anchors and Authentication TF*
*Co-Chair - TCG Trusted Mobility Solutions WG*

*Co-Chair - TCG Metadata Access Protocol SG*








*Chair - Linux Foundation Open Printing WGSecretary - IEEE-ISTO Printer
Working GroupCo-Chair - IEEE-ISTO PWG Internet Printing Protocol WGIETF
Designated Expert - IPP & Printer MIBBlue Roof Music / High North
Inchttp://sites.google.com/site/blueroofmusic
<http://sites.google.com/site/blueroofmusic>http://sites.google.com/site/highnorthinc
<http://sites.google.com/site/highnorthinc>mailto: blueroofmusic@gmail.com
<blueroofmusic@gmail.com>(permanent) PO Box 221  Grand Marais, MI 49839
906-494-2434*

**Comment by jhdalek55** [comment]
I think @patrickvacek has identified a valid concern here. I agree that more specific terminology is called for here. But, I do think if the goal is clarity then we HAVE to consider any potential label from all sides. For the sake of being able to meet our self-imposed deadline, which is that we decide to release as of our next meeting, can we clearly mark this as an issue for 2.0.0?  I'm taken on "the expediter" role for this next version and I just want us all to be on the same page as to what is going to be incorporated into it. By all means, let's keep this discussion going, but can we do so under a 2.0.0. designation?

**Comment by iramcdonald** [comment]
Hi Lois,

Yes, we can push it to v2.0.0.

I think we can resolve appropriate terminology sooner and change it in
v1.2.0.
It's a key practical issue for Uptane deployments in real automobile models
in
the next couple of years.

Cheers,
- Ira

*Ira McDonald (Musician / Software Architect)*

*Chair - SAE Trust Anchors and Authentication TF*
*Co-Chair - TCG Trusted Mobility Solutions WG*

*Co-Chair - TCG Metadata Access Protocol SG*








*Chair - Linux Foundation Open Printing WGSecretary - IEEE-ISTO Printer
Working GroupCo-Chair - IEEE-ISTO PWG Internet Printing Protocol WGIETF
Designated Expert - IPP & Printer MIBBlue Roof Music / High North
Inchttp://sites.google.com/site/blueroofmusic
<http://sites.google.com/site/blueroofmusic>http://sites.google.com/site/highnorthinc
<http://sites.google.com/site/highnorthinc>mailto: blueroofmusic@gmail.com
<blueroofmusic@gmail.com>(permanent) PO Box 221  Grand Marais, MI 49839
906-494-2434*

**Comment by pattivacek** [comment]
No urgency here, but I'm still thinking about how to resolve this. I see a few issues at play here:

1. We need a better name for these ECUs that cannot even perform partial verification and/or that lack any storage. "Legacy Secondary" is imprecise and unclear. "Tertiary ECU" implies that these are somehow subjects of Secondaries, which is inaccurate and confusing. Some other options are "Non-Uptane ECU" or "verificationless ECU", but these are somewhat clumsy.
2. Do we even want to mention these ECUs? It is of course always possible to update them via Uptane up to the point that the ECU cannot perform verification. The server-side and Primary verification can still proceed according to Uptane. This could be something that gets mentioned in the Deployment Best Practices if we don't want to cover this in the Standard directly.
3. Sections [5.4.2.7](https://uptane.github.io/uptane-standard/uptane-standard.html#rfc.section.5.4.2.7), [5.4.3.3](https://uptane.github.io/uptane-standard/uptane-standard.html#rfc.section.5.4.3.3), and [5.4.3.4](https://uptane.github.io/uptane-standard/uptane-standard.html#rfc.section.5.4.3.4) reference ECUs with and without "secondary storage". The language as it is presumably is meant to cover Secondaries that have just enough storage to be able to do partial verification but not enough to store an entire image. These sections should get revised to be clearer about the expectations of these ECUs.

**Comment by mnm678** [comment]
>     1. We need a better name for these ECUs that cannot even perform partial verification and/or that lack any storage. "Legacy Secondary" is imprecise and unclear. "Tertiary ECU" implies that these are somehow subjects of Secondaries, which is inaccurate and confusing. Some other options are "Non-Uptane ECU" or "verificationless ECU", but these are somewhat clumsy.

I like "Non-Uptane ECU", because these ECUs aren't able to perform Uptane verification

>     2. Do we even want to mention these ECUs? It is of course always possible to update them via Uptane up to the point that the ECU cannot perform verification. The server-side and Primary verification can still proceed according to Uptane. This could be something that gets mentioned in the Deployment Best Practices if we don't want to cover this in the Standard directly.

I don't think we need to mention these ECUs in the standard, as they don't actually perform Uptane verification and are therefore missing some in-vehicle security properties, but I think it would be worth describing how to push updates to them in the Deployment Best Practices.

>     3. Sections [5.4.2.7](https://uptane.github.io/uptane-standard/uptane-standard.html#rfc.section.5.4.2.7), [5.4.3.3](https://uptane.github.io/uptane-standard/uptane-standard.html#rfc.section.5.4.3.3), and [5.4.3.4](https://uptane.github.io/uptane-standard/uptane-standard.html#rfc.section.5.4.3.4) reference ECUs with and without "secondary storage". The language as it is presumably is meant to cover Secondaries that have just enough storage to be able to do partial verification but not enough to store an entire image. These sections should get revised to be clearer about the expectations of these ECUs.

I agree, these sections aren't actually refering to ECUs without secondary storage, but to those with limited secondary storage

**Comment by iramcdonald** [comment]
Hi Marina,

"Non-Uptane ECU" - excellent!

I agree that we should never mention them in the Uptane Standard.

Uptane Secondaries with limited secondary storage have a range of
constraints
(they might also have limited CPU performance).  Uptane has no business to
define concrete size of secondary storage.  In my real world experience,
very
constrained ECUs wind up mandating implementation of Delta updates, because
they will *never* have A/B firmware memory.

Cheers,
- Ira

*Ira McDonald (Musician / Software Architect)*

*Chair - SAE Trust Anchors and Authentication TF*
*Co-Chair - TCG Trusted Mobility Solutions WG*

*Co-Chair - TCG Metadata Access Protocol SG*








*Chair - Linux Foundation Open Printing WGSecretary - IEEE-ISTO Printer
Working GroupCo-Chair - IEEE-ISTO PWG Internet Printing Protocol WGIETF
Designated Expert - IPP & Printer MIBBlue Roof Music / High North
Inchttp://sites.google.com/site/blueroofmusic
<http://sites.google.com/site/blueroofmusic>http://sites.google.com/site/highnorthinc
<http://sites.google.com/site/highnorthinc>mailto: blueroofmusic@gmail.com
<blueroofmusic@gmail.com>(permanent) PO Box 221  Grand Marais, MI 49839
906-494-2434*
