### ISSUE TITLE
Make slow retrieval attack prevention a SHALL

### ISSUE THREAD

**Issue by mnm678** [uptane/uptane-standard#194]
In #193, we added a check for slow retrieval attacks to the standard. During discussion in that pr, we decided that this protection should be a SHALL in a future version of the standard.

**Comment by jhdalek55** [comment]
Per our 3/30 meeting, this check for slow retrieval attacks can be labeled as a SHOULD for 1.2.0 and then be made a SHALL for V.2.0.0

**Comment by jhdalek55** [comment]
Can someone open a pull request changing the requested language to a SHOULD?

**Comment by mnm678** [comment]
It looks like #193 already adds a SHOULD, so I think this is just waiting for 2.0.0

**Comment by jhdalek55** [comment]
Ok. No interim 1.2.0 strategy needed.

**Comment by jhdalek55** [comment]
At our Uptane Standards Meeting on 7/20, it was affirmed that this was just awaiting the wording change and that this change can be made now rather than waiting till right before the 2.0.0 deadline. However, we must approve PR #213 (which adds a statement that changes are made in real-time on the repository, but are not considered "official" till the next version is released) and resolve the must vs. shall issue, which will be discussed at the 8/3/21 meeting.

**Comment by jhdalek55** [comment]
PR#213 was merged. Wording changes for 2.0.0. can now be made in agreement with our SHALL vs MUST decision.

**Comment by jhdalek55** [comment]
Need a volunteer to submit a PR changing a SHOULD to a SHALL. I believe this is what must be changed...
"A Secondary ECU SHOULD perform full verification if possible. If a Secondary cannot perform full verification, it SHALL, at the very least, perform partial verification."

**Comment by jhdalek55** [comment]
Please review and approve PR #216 so we can close this...
