### ISSUE TITLE
Add a note about  Uptane costs

### ISSUE THREAD

**Issue by jhdalek55** [uptane/uptane-standard#223]
At the 9/23 workshop, a question was raised about the cost of using Uptane. It was one of several very basic questions about implementing Uptane brought up at the workshop, and so it was decided we needed a line or two in the Standard to address it, even though implementation costs would likely be influenced by factors other than the requirements of the Standard. The sentences should emphasize that if Uptane were to add any cost to the process, it would be modest.

**Comment by jhdalek55** [comment]
There was quite a bit of discussion at the 11/9 Uptane Standards meeting about  what we could say on this topic. One suggestion was to offer some type of anecdotal evidence on the topic by a company that has implemented Uptane (such as HERE, so @pattivacek or @tkfu, could you weigh in on this issue?).  Another line of thought is that, at this point, any expense is going to be more expensive than doing nothing. Adopting Uptane does require some changes to implement and therefore there are costs involved. As a result, and OEMs may feel that accepting the potential risk is a better course of action.

We invite discussion on this thread over the next few weeks. Is there anything of substance we can post about the cost of Uptane, or should we defer this to a later edition of the Standard/Deployment documents.

we would appreciate receiving this feedback prior to our next meeting (on 11/23), as final decisions will need to be made then about what open issues we need to defer to a later version.

**Comment by tkfu** [comment]
I missed that meeting, so forgive me if I'm re-treading ground here.

I think there are basically two paths that an OEM can go down in choosing to implement Uptane: either buy an off-the-shelf solution and do an integration, or build a custom solution, with some greater or smaller degree of reliance on the open-source client and server components.

The relative costs of those two options (and the shades of difference between custom-from-the-ground-up and customizing/modifying the open source solution) are admittedly difficult to estimate.

Off-the-shelf service providers are an interesting option, and can be a very good one, but I can tell you from experience that there are often ways in which the provider and the OEM are misaligned that can make the integration difficult. Additionally, there's a risk profile associated with getting your OTA system from a 3rd party; they could go out of business, or just take their product in a new direction or sunset it, either because of an acquisition or just a change in corporate priority.

Some variant of the custom in-house option, then, is arguably the safest choice for larger OEMs. But it's also the higher-cost, higher-effort option, and the estimation of cost and effort is going to be highly situationally dependent.

I think that one thing you can say with certainty about Uptane is that, if you are building every component of your update system from the ground up, it won't add much extra effort to follow Uptane. In fact, it'll probably make your life easier by writing down a bunch of things that you need to think about in advance. But greenfield projects are almost never the reality. It's always an integration with various legacy systems, and anyone who's done projects like that knows that the devil is in the details.

**Comment by JustinCappos** [comment]
This is great!  I'd like to propose that we figure out a good way to add
this to the documents so that others can benefit from your wisdom on the
topic.

**Comment by jhdalek55** [comment]
We could add this text to the Deployment best practices, perhaps towards the end of the "Setting up Uptane repositories" section, as it would likely be a discussion to make when Uptane is initially implemented.

**Comment by pattivacek** [comment]
> In fact, it'll probably make your life easier by writing down a bunch of things that you need to think about in advance. But greenfield projects are almost never the reality. It's always an integration with various legacy systems

I don't think I have much to add here, but this part got me thinking. I see three main ways of implementing Uptane:

1. Greenfield project: the extra cost will be minimal, because you need an organized way of developing a secure system anyway, so why not just use Uptane?
2. Upgrading a legacy solution: most likely you're going to want to do a risk assessment of the current solution and evaluate where the current weaknesses and major opportunities for improvement are. Again, you need an organized way of doing that assessment, so why not compare with Uptane? The cost may be *cheaper* than trying to do something like that without an existing framework.
3. Integrating with a third-party: this is tricky to estimate, but if you're outsourcing OTA, it's not going to be free one way or another. I can't say whether Uptane solutions on the market are more expensive than others, but again, if you're trying to evaluate options, using Uptane as a standard to compare against sounds easier than doing it without a framework.

None of that directly addresses the actual costs, but I can't really speak to that anyway. The way I see it, though, the have to do similar work one way or another (or just take shortcuts and sacrifice security). So Uptane isn't adding cost; you can look at it like a framework for organizing the development or risk assessment that you're going to have to do anyway. I guess I'm assuming that you want a security system in the first place, but I think that goes without saying.

**Comment by tkfu** [comment]
Yeah, I think the implication of the cost question is, in fact, usually about the cost trade-off between taking shortcuts and sacrificing security or doing it right and spending more time/money. For example, robust key rotation is one of the most important pillars of TUF and Uptane, but it's also something that, in my experience, companies are often fully prepared to throw out the window if they think it will save money. Obviously I don't think that's a good trade-off to make, but it's common enough.

**Comment by jhdalek55** [comment]
@jhdalek55 agreed to blend @tkfu and @pattivacek comments into a PR for 2.0.0.

**Comment by jhdalek55** [comment]
See PR #122 on the Deployment page

**Comment by jhdalek55** [comment]
We can close this by approving PR#122 on the Deployment page

**Comment by jhdalek55** [comment]
Closed via approval of Deployment PR#122 on12/17/21
