### ISSUE TITLE
Licensing for Uptane Standard

### ISSUE THREAD

**Issue by jhdalek55** [uptane/uptane-standard#243]
I have taken a quick look and I can't find any licensing statement mentioned either in the Standard or on the repository. Do we not have one? Or is this just an oversight in terms of making mention of it on the repo? Or is this not needed because we are under the auspices of a Standards organization?

**Comment by iramcdonald** [comment]
Hi Lois,

No, we definitely need explicit licensing for the Standard and Deployment
Considerations
and any other public artifacts (white papers, slide sets, etc.) on our
website.

For the Standard and Deployment Considerations (because they're frameworks
with
concrete requirements), Apache v2 would be most appropriate (a superset of
BSD and
MIT).

Both IEEE-ISTO Printer Working Group and LF OpenPrinting migrated all their
code and
design documents to Apache v2 about five years ago.  Seth Newberry at JDF
says it's the
best choice in most cases.  Every version of GPL/LGPL is intellectual
property poison and
should never be considered.

https://www.apache.org/licenses/LICENSE-2.0
https://en.wikipedia.org/wiki/Apache_License#Apache_License_2.0

For everything else (except for white papers - which are design documents -
Apache v2),
probably Creative Commons.  It's dominant in academic papers, music, and
other arts.

https://creativecommons.org/licenses/
https://en.wikipedia.org/wiki/Creative_Commons_license

Cheers,
- Ira


*Ira McDonald (Musician / Software Architect)*

*Chair - SAE Trust Anchors and Authentication TF*
*Co-Chair - TCG Trusted Mobility Solutions WG*

*Co-Chair - TCG Metadata Access Protocol SG*








*Chair - Linux Foundation Open Printing WGSecretary - IEEE-ISTO Printer
Working GroupCo-Chair - IEEE-ISTO PWG Internet Printing Protocol WGIETF
Designated Expert - IPP & Printer MIBBlue Roof Music / High North
Inchttp://sites.google.com/site/blueroofmusic
<http://sites.google.com/site/blueroofmusic>http://sites.google.com/site/highnorthinc
<http://sites.google.com/site/highnorthinc>mailto: ***@***.***
***@***.***>(permanent) PO Box 221  Grand Marais, MI 49839
906-494-2434*

**Comment by jhdalek55** [comment]
Thanks @iramcdonald. Any volunteers out there that could help me work on this?

**Comment by hexsecs** [comment]
For whitepapers, slides, etc, I suggest CC BY-SA or possibly CC BY. Share-alike, could be tricky the Uptane slides are part of slides that have information that cannot be shared.

**Comment by hexsecs** [comment]
For the standard itself, https://choosealicense.com/licenses/ does a great job describing the different tradeoffs of licence types.
