### ISSUE TITLE
Delegations should apply to Hardware Identifiers, not Target Names

### ISSUE THREAD

**Issue by cajun-rat** [uptane/uptane-standard#29]
I've been looking a bit deeper into the Delegations part of the Uptane spec, and I think the current design isn't powerful enough to represent trust relationships like "I trust this Tier 1 supplier to provide updates for the ECUs that they manufacture"

Delegations today provide permissions like "Supplier A can sign-off any image with a name that matches foo/*". This works fine for TUF, but Uptane has a separate concept of a Hardware Identifier that binds an image to a specific type of hardware.

When ECUs verify an image, they are not required to consider the name of the target at all:

https://uptane.github.io/uptane-standard/uptane-standard.html#verify_image

This means that--as spec'ed--delegations effectively allow the supplier to sign images for any ECU on the system. Just because I'm forced to name my target 'suppliera/...' doesn't mean I can't include an image in that delegation with a Hardware Identifier belonging to Supplier B.

I can see two fixes for this:

1. During image installation (Verify Image), check that the path for a target matches some pre-configured prefix.
2. Change delegations to delegate a subset of Hardware Identifiers, rather than a subset of paths

I think the second is the best solution: The first will break a bunch of devices in the field, and will be too easy to implement incorrectly.

Assuming my analysis is correct, and there isn't something that defends against this already, I propose that delegations should be made to a set of Hardware Identifiers only. Specifically:

* Remove the clause that says delegations contain "A list of the images or paths to which this role applies. This MAY be expressed using wildcards, or by enumerating a list, or a combination of the two."
* Instead say that delegations contain a "List of Hardware Identifiers"

**Comment by lbonn** [comment]
That's a very good point, I agree.

However, I believe that using a list of hardware identifiers would only cover first order delegations as it doesn't leave room for building a hierarchy of suppliers. Still, the question remains whether higher order delegations are part of a realistic deployment case, as an OEM will probably want to control the global list of possible hardware ids in a  vehicle.

**Comment by cajun-rat** [comment]
See PR #33 which fixes this issue

**Comment by jhdalek55** [comment]
Phil, if PR #33 has addressed the problem, can we close this issue?

**Comment by awwad** [comment]
That PR isn't merged yet, so we'd have to wait.

**Comment by jhdalek55** [comment]
Ok. It looks like there a merge conflict on #33. Is that why this is awaiting merger or are decisions still to be made on the copy? We currently have a lot of open issues and I just want to be aware of the status of each of them.

**Comment by awwad** [comment]
The conflict isn't really an issue; I'll fix it now.  The rest I'll discuss on that PR itself.

**Comment by jhdalek55** [comment]
Thanks, Sebastien. Just trying to do a little housecleaning to see what 
is or is not being addressed.


Lois

On Thu, Feb 21, 2019 at 11:36 AM, Sebastien Awwad wrote:

The conflict isn't really an issue; I'll fix it now.  The rest I'll 
discuss on that PR itself.


—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub 
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_uptane_uptane-2Dstandard_issues_29-23issuecomment-2D466069819&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hgBKIqNYIOwzXeBjPUaKRw&m=6lAa2YihC_an5NL_EgdUCcJxZMEC2hwINC89kroGDfo&s=5eUpABkC3PL_8h0vJsuWOfrIvVyfSJi_d8YeOi5_T30&e=> 
, or mute the thread 
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AN5qX-5FXD0KUng-5FAuWjNWWcEtvqf1vAGwks5vPssngaJpZM4aao2g&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hgBKIqNYIOwzXeBjPUaKRw&m=6lAa2YihC_an5NL_EgdUCcJxZMEC2hwINC89kroGDfo&s=zK_MV_sOjmreIo0DWfk-QkmpzawMy_iyJo9Xi3cSkmE&e=> 
.

**Comment by cajun-rat** [comment]
I've updated PR #33 to fix the merge conflicts

**Comment by JustinCappos** [comment]
Fixed in #33.
