### ISSUE TITLE
Ambigious Assumption: "Vehicles have regular connectivity established."

### ISSUE THREAD

**Issue by JosiahOne** [uptane/uptane-standard#30]
In Section 3.2.1 (https://uptane.github.io/uptane-standard/uptane-standard.html#rfc.section.3.2.1) of the standard, the first assumption presented is that:

> "Vehicles have regular connectivity established. The common scenario is cellular connectivity, but Uptane could also be applied via other communication channels such as WiFi and even wired connections."

I am worried this is overly ambiguous and may scare away potential implementers. What does "regular connectivity" mean here? Normal?

If so, does Uptane fail to work for vehicles who have subpar connectivity (poor location, limited data plans, etc.)? I'm pretty sure the answer is no, Uptane works fine.

I think the real assumption is more along the lines of: "Vehicles are capable of establishing connectivity".

**Comment by JosiahOne** [comment]
Actually, limited data plans are explicitly mentioned as an exception in Section 3.3 (https://uptane.github.io/uptane-standard/uptane-standard.html#rfc.section.3.3)

**Comment by iramcdonald** [comment]
Hi,

I agree with Josiah's comments.  I strongly disagree with *explicitly*
mentioning
cellular connectivity at all for vehicles in Uptane standard.

Given current IEEE 802.11 NGV activity (now chartered as 802.11bd task
group),
it is quite likely that, in some geographic regions, high-speed urban Wi-Fi
will in
fact be the preferred V2X connectivity choice (including in safety
regulations).

Also, as Josiah noted, low bandwidth and intermittent V2X connectivity
should
not rule out Uptane functionality.  In 90% of the continental US, there
will *never*
be good quality cellular coverage (that number comes from the Sprint CTO's
security team two years ago) - due to the need for several trillion dollars
of
new cellular base stations.  Basic physics says that much higher 5G cellular
speeds are going to greatly reduce the range of cellular base stations.

Cheers,
- Ira


Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by JosiahOne** [comment]
I opened https://github.com/uptane/uptane-standard/pull/32 which resolves this in my mind.

Of course, review/feedback is needed and encouraged.
