### ISSUE TITLE
Security vulnerabilities involving time

### ISSUE THREAD

**Issue by sam-m-weber** [uptane/uptane-standard#31]
There seems to be two (related) security vulnerabilities present in this version of the specification.  The impact of each of these vulnerabilities is that the ECUs in an affected vehicle will be unable to ever be updated in the future, and I believe that both of these attacks are easily mountable.

Both of these vulnerabilities involve an attacker successfully compromising the time server (or other source of time, if Uptane's time server isn't used).

### Vulnerability One

According to the current specification, in the section "Downloading and distributing updates on a primary ECU", the second step in the process is "Download and check current time".  Consider the effect if an attacker causes the time server (or other source of time) to return MAXINT (the greatest possible time) as the current time at this stage.  The update process will then proceed with the ECU's current time being set to MAXINT.  

After this occurs, the primary ECU will forever be unable to perform any updates, even after the time server has been recovered.  This is because the "current time" has been set to MAXINT, this cannot be changed, and all future updates will fail at the second step.

Because of the second vulnerability, as-is this attack will be limited to the primary ECU.  However, if the second vulnerability is addressed, then step 5 of the primary's update process "Send latest time to secondaries" will occur.  The secondary ECUs' update process has the same flaw and they also will be similarly affected. 

### Vulnerability Two

Both the full and partial verification processes are vulnerable to a time attack.  If the "latest attested time" is MAXINT, then
- The Partial verification process will fail in step 5, with the ECU reporting an error code indicating a freeze attack
- The Full verification process will attempt to load new versions of the Root metadata file, only to fail in step 3.iii, reporting a freeze attack.

In either case, once the attack has been performed, verification will fail every time an update is attempted, even after the time server has been recovered.

### Conclusion

In the current specification, if an attacker is able to compromise the time server (or other source of time) then they can cause vehicle ECUs to be permanently unable to be updated.  Both the core update process and the verification processes seem to have issues that should be addressed.

I do have a possible fix to these problems -- I'll describe it in the discussion.

**Comment by sam-m-weber** [comment]
Here is my proposed solution to the vulnerabilities described.  I know that it is a non-trivial change to the specification, but I think it not only solves the issues but makes the update process simplier.

Briefly, I'd like to remove the knowledge of time from Uptane -- time is difficult to establish and make secure.  (Notice that in the current specification the time server needs a cryptographic key, but there is no process established to update this key except to replace all the firmware images of all the ECUs. If a time server isn't used in a particular implementation, it is almost certain that whatever mechanism is used also needs some sort of cryptographic key which likewise will need to be updated by an unspecified process.)

The property that Uptane actually needs is freshness: the assurance that a message that is received by a party was actually generated recently and not replayed.  As far as I can tell, almost all of the uses of time in Uptane are meant to establish freshness.  (The exception seems to be to force keys to expire, and I believe that are other ways to deal with that.)

Luckily, nonces can be used to establish freshness.

Here is an alternate protocol for updates:
  1. The primary asks the director for a nonce.  (Call it "nonce1")
  2. As before, the primary constructs the manifest.  It sends this to the director along with nonce1 (which it signs), and with its own nonce and the nonces of its secondaries.  (In the existing protocol, these nonces were sent to the time server.)
3.  The director will verify that the manifest message includes nonce1, showing that this isn't a replayed manifest.
4. In the director's response it will include the nonces of the primary and all of the secondaries, proving to the vehicle's ECUs that this message is newly generated in response to the latest manifest.

I think doing this will solve the issues with time.  I do realize that this is a non-trivial change, however, and will likely require some thought.

**Comment by JustinCappos** [comment]
Thanks for weighing in!  I think this issue is a misunderstanding in the
spec.  If the time server's key is revoked, then the time information it
provided is discarded.  (The same issue you mention here would exist for
version numbers in files, etc. but is handled by discarding the old data
when the key changes as is detailed in the Mercury paper.)

We will make a pass and be sure that there is no confusion for any
implementer.  I appreciate the effort to point out that this wasn't clear!

Thanks,
Justin

**Comment by sam-m-weber** [comment]
No, this is not a misunderstanding.  If you read the section "Downloading and distributing updates on a primary ECU" you'll see the time is checked in step 2, BEFORE any key revocation is done.  And, in the Full verification process a failure will be reported when attempting to update the Root metadata.

**Comment by awwad** [comment]
Justin and I discussed this fast-forward attack some time ago and IIRC we had a less damaging solution along the lines of what Justin outlined above.  It's possible that the spec hasn't captured the order correctly.  (It's necessary for the root role's change of the timeserver key to occur even if the current time on the ECU seems to be past the new, timeserver-key-revoking root metadata's expiration time.)  I'm looking through today and I'll provide my take on both specs and the reference implementation.  Thanks for bringing this up!

**Comment by awwad** [comment]
Fast-forward attacks relying on time or version numbers are all resolved by the same basic approach as that in the Mercury paper (using a higher-trust role to reset that time/version information).  We discussed these Uptane extensions of that defense in late 2017, but there was some debate because of partial verification ECUs, and it seems I didn't update the implementation specification at the time, so **the Uptane Standard needs to be updated**.  (The changes we came to are fairly straightforward and I'll add them there to handle both partial and full verification.)

**The reference implementation** already allows root to be verified even if the clock tells us that the new root metadata is expired.  This was important for root chaining, and allows us to protect against this fast-forward attack, too.  I haven't yet implemented the Timeserver key rotation mechanism (via Root and Targets) in the reference implementation, though.  (Sorry, this ASN.1 thing has been taking more of my time than I thought possible.)

Moving from clock-based expiration to nonces/tokens more broadly is a more drastic change.  Thoughts there, @JustinCappos?

**Comment by JustinCappos** [comment]
Well, Sam's proposal is pretty similar in spirit to the use of HTTPS to
talk with the director and to avoid the use of the time server that way.
To me this feels like a pretty similar piece of functionality for groups
that are willing to have a different threat profile.

Maybe putting it in the deployment considerations next to that discussion
makes the most sense?  If so, I'd like to think more about it and have us
analyze it more to be sure we can accurately talk about it.

**Comment by trishankatdatadog** [comment]
0.02 BTC: in 2019, TLS between the director / image repositories and
primaries may just be safely assumed. I believe Ira has been calling
strongly to mention TLS, too. If so, should we just get rid of the time
server complication from the standard altogether?

**Comment by jhdalek55** [comment]
What about this issue. Did #41 address the concern?

**Comment by awwad** [comment]
@jhdalek55 I think it addresses the vulnerabilities discussed.  Thoughts, @sam-m-weber?

The question of the use of the time server overall is larger, and I don't know if this issue should be kept open to address it, or if it belongs somewhere else.

**Comment by sam-m-weber** [comment]
I'm afraid I don't think this does fully address the issue -- the primary still checks to see if the new time is greater than the current time and won't go further in the update process if it isn't.

**Comment by awwad** [comment]
> I'm afraid I don't think this does fully address the issue -- the primary still checks to see if the new time is greater than the current time and won't go further in the update process if it isn't.

I don't understand:
Can you clarify how [this](https://github.com/uptane/uptane-standard/pull/41/files#diff-aaf9170627e7d94a7c20fa9ef96f3ae1R827) does not resolve that issue?  The clock is reset before that check occurs, if the timeserver key is changed....

**Comment by sam-m-weber** [comment]
Not according to my reading of the document.  In the section "Downloading and distributing updates on a primary ECU" it says:

> it SHALL perform the following seven steps:

>1. Construct and send vehicle version manifest ({{construct_manifest_primary}})
>2. Download and check current time ({{check_time_primary}})

And at this point the update process will stop,

**Comment by awwad** [comment]
No.  You'd check the current time.  You check the time attestation's signature and update your clock.  That's all that happens there.

**Comment by awwad** [comment]
Ahh, I think I see the confusion here.  When I read your earlier message ([this](https://github.com/uptane/uptane-standard/issues/31#issuecomment-466157372) one), I I incorrectly read it as referring to the full verification algorithm (since that's where there is an actual fast forward attack issue, and that's where it's fixed by the PR).

The part you're pointing to instead -- {#check_time_primary} -- doesn't (and shouldn't) halt the update process if the time attestation is not verified.  (If someone else intended for that to be what happens here, then that's wrong.)  If the time attestation is verified, it updates the clock.  If not, it does not update the clock.  That doesn't halt the update.  I don't think it says it does anywhere.  Perhaps we should make sure that's clear.

**Comment by JustinCappos** [comment]
Yes, please clarify this point.  Better safe than sorry.

**Comment by jhdalek55** [comment]
Planning to take a look tomorrow at this and at anything else that 
appears to be purely semantic issues.


Lois

On Sun, Feb 24, 2019 at 07:13 PM, Justin Cappos wrote:

Yes, please clarify this point.  Better safe than sorry.


—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub 
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_uptane_uptane-2Dstandard_issues_31-23issuecomment-2D466833353&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hgBKIqNYIOwzXeBjPUaKRw&m=QBUb32K6njETyc2akB_JVRhLK14qZFSVGNdApDRkOjc&s=H6hnLVnYPE8Us0UsymCVx4qLrXcMvlTZtk73k6NxBuQ&e=> 
, or mute the thread 
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AN5qX0PcZ7KAc-5FzNil1eacjOmphKrUFhks5vQyqegaJpZM4amN-2DC&d=DwMCaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hgBKIqNYIOwzXeBjPUaKRw&m=QBUb32K6njETyc2akB_JVRhLK14qZFSVGNdApDRkOjc&s=u6PwW8hI3C7QReL1oreWvH93_gmynvyZ01DvmsFIYSI&e=> 
.

**Comment by sam-m-weber** [comment]
The wording does need to be changed, alas.  #check_time_primary says "Verify that the signatures are valid, and that the time the server attests is greater than the previous attested time."  In many other places in the document the word "verify" means that it is an error if the condition is not true.  (Which is also the common meaning, I think.)

**Comment by jhdalek55** [comment]
I'd be happy to try to correct this, but I just want to clarify the issue. Are we questioning how the word "verify" is used across the board? If so, that's obviously a much bigger issue.   Let me know.

**Comment by awwad** [comment]
So, it just needs to be clear in the document that:
- If a time attestation is verified, the device's time is updated.
- If a time attestation is not verified, the device's time is not updated, but neither do we abort any of the algorithms in which this occurs.

It's probably a short addition.

**Comment by iramcdonald** [comment]
Hi,

While I agree with the spirit of Sebastian's reply, I note that it's
actually
important (eventually) that we *never* use either the word "verify" or
"verification" except in a formal algorithm, where *normally* an abort
is the correct result of a failed "verification" step.

In this particular case, there are two levels of algorithms that are too
informally intertwined (i.e., updating local notion of time versus the
acceptance criteria for *other* metadata).  Bad spec language, IMO.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by JustinCappos** [comment]
FYI: @awwad is adding a unit test for this case to the test suite.  We'll also fix the language as discussed above.

**Comment by tkfu** [comment]
On the 03/13 standards call, @JustinCappos said that @awwad was working on these issues. We'll look at it again on the next call.

**Comment by awwad** [comment]
A branch of code on [Uptane PR #171](https://github.com/uptane/uptane/pull/171) demonstrates this timeserver fast-forward attack resolution via timeserver key rotation.  The test code is visible [here](https://github.com/uptane/uptane/blob/59b4ca2900d1c21ede512ec985906afcfca11c14/tests/test_secondary.py#L864-L1085) and a test run showing the test succeeding is visible [here](https://travis-ci.org/uptane/uptane/builds/511733483#L1468-L1519).  (There's an unrelated test failure there that I'll clean up shortly.)

Note that this code will not be merged in the reference implementation yet because the support provided on that branch is JSON-only: changes to the ASN.1/DER metadata definitions are frozen due to an ongoing rewrite occurring in parallel on the main TUF codebase.

**Comment by awwad** [comment]
Before we can actually close issue, the [{check_time_primary}](https://github.com/uptane/uptane-standard/blob/762a92857bee6554d3d479e1f5b5b8e6a4857f68/uptane-standard.md#download-and-check-current-time-check_time_primary) section of the standard still requires clarification.  Specifically, as noted above:
- If a time attestation is verified, the device's time is updated.
- If a time attestation is not verified, the device's time is not updated, but neither do we abort any of the algorithms in which this occurs.

As Ira noted above, we should avoid the use of "verify" in any way that could suggest that the update procedure aborts if the time is not updated.

@jhdalek55, is this something you're taking on, or should I write something?

**Comment by jhdalek55** [comment]
Very early on in this discussion I said I would do something with this, but if you have the time, you seem to be better positioned to write it than me. I can wordsmith drafted text if needed.

**Comment by jhdalek55** [comment]
On the 3/27 Standards call, this issue was left open pending completion of text.

**Comment by jhdalek55** [comment]
I opened PR#93 to address the wording issue that remained in this issue. Please review and let me know if this is sufficient.

Lois

**Comment by jhdalek55** [comment]
@tkfu @trishankatdatadog  can one of you check this verbiage and approve so we can merge this and close out Issue 31? Thanks.

Lois

**Comment by trishankatdatadog** [comment]
@jhdalek55 Looks like you guys are handling this already :)
