### ISSUE TITLE
Updating primary

### ISSUE THREAD

**Issue by sam-m-weber** [uptane/uptane-standard#44]
According to the section "Downloading and distributing updates on a primary ECU" the primary will never be updated.  This is probably not what is intended. :-)

**Comment by awwad** [comment]
The section you refer to, "Downloading and Distributing Updates on a Primary ECU" ([permalink to today's](https://github.com/uptane/uptane-standard/blob/995bf57f3e32096cf34ba2635d9d02ee063207b1/uptane-standard.md#downloading-and-distributing-updates-on-a-primary-ecu); [live doc](https://uptane.github.io/uptane-standard/uptane-standard.html#rfc.section.5.4.2))  specifically relates to what primaries do to download and distribute updates, which is why it does not talk about image installation on any ECUs.

We could clarify the next Section 5.4.3 ("Installing Images on ECUs" -- [permalink to today's 5.4.3](https://github.com/uptane/uptane-standard/blob/995bf57f3e32096cf34ba2635d9d02ee063207b1/uptane-standard.md#installing-images-on-ecus); [live 5.4.3](https://uptane.github.io/uptane-standard/uptane-standard.html#rfc.section.5.4.3)) to make very clear that the Primary performs the same steps as Secondaries to update itself.

I guess we could instead broaden the section you refer to to make it about what the Primary does, overall, rather than just about its obtaining and distributing updates.

@JustinCappos  Preference?

**Comment by sam-m-weber** [comment]
I'd prefer to make the section "what the primary does", because otherwise you'd have the primary verifying the metadata, downloading the images, etc, twice, which nobody would implement.

**Comment by JustinCappos** [comment]
I think Sam's suggestion makes sense.  Please make the change.

**Comment by JosiahOne** [comment]
This was fixed in https://github.com/uptane/uptane-standard/pull/85

**Comment by jhdalek55** [comment]
Closed 3/27 after confirmation on the Standards conference call that the issue had been addressed in PR#85
