### ISSUE TITLE
Error Codes

### ISSUE THREAD

**Issue by sam-m-weber** [uptane/uptane-standard#45]
If full or partial verification fails, then the specification states that an error code should be returned.  To what, and how?  The only place I see reference to this elsewhere is in the ECU version report -- will an update failure only be noticed when the next version report is generated?  And will the primary update itself (assuming issue 44 is fixed) even if one of the secondaries has failed?

**Comment by awwad** [comment]
> If full or partial verification fails, then the specification states that an error code should be returned. To what, and how? The only place I see reference to this elsewhere is in the ECU version report -- will an update failure only be noticed when the next version report is generated?

The ECU version report is what we expected, yes, and it can be generated in response.  If implementers want to provide the report immediately or in the next cycle, that's up to them, I think.


> And will the primary update itself (assuming issue 44 is fixed) even if one of the secondaries has failed?

I think we've regarded questions of dependency resolution like this out of scope, since the OEM (or whoever is directing) may want or need to do things differently from other OEMs.  I don't think this standard (correct me if I'm wrong) currently requires a particular result in that scenario.

**Comment by awwad** [comment]
Closing as answered, but if there are other questions, or if I'm missing something, feel free to follow up.
