### ISSUE TITLE
Role definitions

### ISSUE THREAD

**Issue by sam-m-weber** [uptane/uptane-standard#47]
The definition and descriptions of "roles" seem inconsistent and unclear to me.  In the "Uptane Role Terminology" and "Roles on repositories" sections the roles are described as active entities; "Distributes and revokes..." etc, but aren't actually defined.  The impression gained is that a role is simply a public/private key pair that is used for one of four or five possible purposes in Uptane.  Could the wording be made clearer?

(I had previously put this in with a number of other small clarification requests, but Justin requested that I raise it as its own issue.)

**Comment by tkfu** [comment]
So, in my view a "role" is an abstract concept denoting an area of responsibility within the security framework. The real elements that comprise a role are:
1. The role metadata
2. The signing keys for the role

So, you have root metadata and root keys, targets metadata and targets keys, etc.

That being said, the question of what the heck a role is comes up a lot, and I'm less and less convinced that it's a useful concept. Almost always, when we're talking about one of the roles, we're either talking about its metadata or its keys--rarely is it useful or necessary to refer to the two together.

I understand that this would be a pretty radical change in the way we communicate, but maybe we could expunge the idea of "roles" altogether. Instead, we could talk about _types_ or _kinds_ of metadata, and the signing key(s) that secure that metadata.

**Comment by trishankatdatadog** [comment]
@tkfu I agree it's confusing to refer to both when we almost always mean one or the other (keys or metadata). At the same time, we do need a word to refer to the party (a.k.a. the role, whether man or machine) that will be signing the metadata using the key. I think as long as we make the distinction between all three super-clear, we should be fine.

**Comment by JustinCappos** [comment]
We've worked on this a bit, specifically @Marina Moore <mnm678@gmail.com>,
trying to make this consistent.  We'll take another look for clarity.

**Comment by awwad** [comment]
It's a lot easier to define roles in a world without targets delegations.  Recall that a delegation is a construct that imposes key and threshold expectations on a role.  Roles and delegations are distinct.

It's possible that this observation is not helpful at the level of these explanations....  Something to consider, at least....

**Comment by jhdalek55** [comment]
I have been holding off on offering any input in these discussion because I wanted to make sure the technical questions were answered before I suggested pure wording changes. I actually think, though, that Sebastien's observation that Roles and Delegations are distinct is important. However, doesn't a delegation carry out the same essential tasks as a role? Or am I misunderstanding something important here?

I will take a look at Marina's text as soon as I can. But, first I'd like to make sure my understanding of these terms is clear.

**Comment by mnm678** [comment]
The terms for roles, role keys, and role metadata are not well separated in the specification. I think that the concept of roles is still useful, especially when considering thresholds and delegations. I can go through and clarify the uses in the specification. How do the following definitions look:

* Role: a party (or machine) responsible for signing a certain type of metadata. The role controls keys and is responsible for signing metadata with these keys.
* A role's keys (referred to as 'the root role's keys', etc): the key(s) associated with a role that are used to sign that role's metadata
* A role's metadata: the metadata associated with a role that must be signed by that role.

**Comment by iramcdonald** [comment]
Hi Marina,

Yes - good definitions.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by mnm678** [comment]
I updated the definition of a role in the pr (#60).

**Comment by tkfu** [comment]
> At the same time, we do need a word to refer to the party (a.k.a. the role, whether man or machine) that will be signing the metadata using the key.

@trishankatdatadog (and others): Why do we actually need this word/term? Can you point to the places where having a specially defined term meaning "the person or entity who signs a type of metadata" makes things clearer? Are there enough of those places to make it worthwhile to keep the term "role" around? What if we examined the places where we actually use the term role, and replaced that term with "the [person|process] that signs the [targets|snapshot|root|timestamp] metadata"? Are there really so many places where we use the concept of role (i.e. places where it's impossible to simply refer to the metadata or the keys alone) that it is worth the cognitive load of explaining the term?

## Let's get linguistic

There's a key finding in cognitive linguistics that most good technical writers know about, either explicitly or implicitly. It can be summarized as "humans are bad at substitution and abstraction", and it's mostly instrumentalized as advice to avoid using acronyms and abbreviations much as you possibly can--the space and time they saves actually comes at a surprisingly high cognitive cost, and often ends up being self-defeating.

Why is that? Well, when you use an abbreviation that isn't immediately familiar to your reader, they will employ one of two strategies:

1. Look up the term. In the best case, this is a "mental lookup": the reader is jolted out of the flow of the text, brings up their recall of the term into surface consciousness, and mentally substitutes the abbreviation or acronym for its actual meaning. If the reader can't find the term just by trying to perform the recall-and-substitute operation, then the "lookup" strategy is literal: the reader goes to reference material to try to find the definition. Either way, the efficiency that you hoped to gain by using the abbreviation is lost, and you're left in a worse situation that you would have been had you just written out the whole term/idea/definition.
2. Ignore the fact that they don't understand the term, skim past, and hope to develop an understanding from context and/or fill in the blanks later.

The cognitive load of strategy 1 is high, and if it's too high, it pushes people towards strategy 2. Strategy 2 leads to misunderstandings, and misunderstandings in standards lead to bugs in implementations.

## The discussion so far

I have yet to see anyone actually defend the case for using the concept/term "roles". In the discussion above:

* Trishank asserted that we need a word for it, but didn't really address why "the targets role" is better than "the person who signs the targets metadata". 
* Sebastian pointed out that the term "role" is in fact even harder to accurately define in the context of delegations.
* Marina asserted that the concept is useful, but didn't say why, except that they're "useful when considering thresholds and delegations", which would seem to be at odds with Sebastian's point.

I'm not 100% certain whether ditching the "roles" term is a good idea or not, but I'd like to suggest that the folks advocating for using the term may be more influenced by inertia than by carefully considering its usefulness in communication. Can anyone offer a better reason for why it's necessary?

**Comment by trishankatdatadog** [comment]
@tkfu So long as we are confident that Uptane implementors are never going to read any of the TUF specifications and proposals, and not get confused about the differing terminology, I'm not married to the idea of having the use the word "role."

**Comment by jhdalek55** [comment]
It's true that our ultimate goal here is clarity and therefore we need to
take a hard look at every term we might use, even ones that are legacies
from Uptane's TUF predecessor. If you look back at the way roles are
defined in TUF, it sound like there is more involved than just signing
metadata. On the TUF web site it reads  "TUF uses roles to define the set
of *actions* a party can perform. The concept of roles allows TUF to *only
trust information *provided by the correctly designated party." The concept
of roles seems crucial to the idea of separation of trust, one of the tent
poles of Uptane's design.

However, if this all boils down just to who or what can sign metadata, then
perhaps its use should be reconsidered. My only two cautions are: 1) it's a
concept that has been part of Uptane's design from the beginning so its
removal could cause confusion, and 2) "person who signs metadata" is a
rather clunky phrase to use repeatedly.

**Comment by jhdalek55** [comment]
I wrote my response before I saw Trishank's, but its essentially the same
point. These are "legacy" terms from TUF.

Lois

**Comment by mnm678** [comment]
I think that the term role is helpful in situations where there is more than one "person" signing the metadata. There may be a threshold of keys - all associated with the same role - that are needed to sign metadata. The use of role allows this to be talked about as "the role signs the metadata" rather than "a threshold of keys associated with the metadata signs the metadata" which I think offers some simplicity for the reader. 

That being said, if the term is causing more confusion than clarity it should probably be reconsidered.

**Comment by iramcdonald** [comment]
Hi,

My two cents - please *keep* the term "role" - it appears almost
universally in recent IETF architecture specs across the whole
spectrum of Internet protocols.

Marina made a good point about "role" to help to clarify the case
where threshold cryptography is used, which might well become
very relevant to Uptane implementations in the future due to laws
and regulations that cut across industries.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by patrickvacek** [comment]
> So long as we are confident that Uptane implementors are never going to read any of the TUF specifications and proposals

As someone that just implemented delegations over the last couple months, it is entirely unrealistic to expect an Uptane implementer to be able to ignore TUF. In fact, I ended up using the TUF spec more than the Uptane spec, although to be fair, I'm more familiar with Uptane than with TUF.

I'm not sure where I fall on this argument, but again, as an implementer, I found the distinction between the four "main" roles and the delegated roles to be confusing, and writing reusable code around these concepts is a challenge. That won't necessarily change just by removing the word "role", but I do wonder if there is a better way to describe these actors and actions.

**Comment by trishankatdatadog** [comment]
@patrickvacek 💯

**Comment by jhdalek55** [comment]
If this is just a wording issue, I'd be happy to take a run at clarifying
things. I would like to ask , though, precisely what is vague or confusing
about these terms. I have worked on TUF project write-ups since the
beginning of my stay here, so maybe I have just absorbed the terminology.
If someone can articulate what is unclear, I'd be happy to propose some
edits.

Lois

**Comment by patrickvacek** [comment]
> I would like to ask , though, precisely what is vague or confusing about these terms. I have worked on TUF project write-ups since the beginning of my stay here, so maybe I have just absorbed the terminology.

I'm also somewhat infected by that problem as well at this point. However, delegations are interesting because we treat them slightly differently than other roles. They only exist in the images repository and they aren't quite as tightly controlled and specified as the four "main" roles. So right there is one opportunity for improvement: how do we describe those four required roles as opposed to the optional unlimited number of delegated roles?

As an implementer, I find it critical to understand which parts of the roles share functionality so that I can reuse the same code for those roles. I ended up refactoring a lot of code that we'd previously only had in the Root role to a parent class inherited by both the Root and all Targets (including delegated) roles, particularly for signing other roles. Describing that as "confusing" was perhaps hyperbole on my part, but reusing the same language for both actions, or otherwise making it clear which actions are similar or even identical, might be helpful. I realize that these might be concerns for the deployment considerations.

**Comment by JustinCappos** [comment]
@awwad Can you chime in about code reuse?  I'd imagine much of the signing, etc. code is identical.  You can't actually tell if a targets file is the top level target's role or a delegated role by looking at it, so I would imagine this code would be identical...

**Comment by jhdalek55** [comment]
Ok, so what I take from Patrick's opening comments is we may need a
different term to label those image repository roles and at the very least,
just a better explanation as to why these delegated roles may behave
differently than the four principle roles we discuss?

I will leave the coding issues to those who know better.

Lois

**Comment by awwad** [comment]
> @awwad Can you chime in about code reuse? I'd imagine much of the signing, etc. code is identical. You can't actually tell if a targets file is the top level target's role or a delegated role by looking at it, so I would imagine this code would be identical...

#### Code Reuse for Top-level Targets and Delegated Targets
Yes, the same code handles almost everything about these two in the reference implementation.  The main difference is that Targets is always verified based on Root, so it can be verified without being concerned about a particular traversal of the delegation graph, and that Targets is refreshed whenever it has been changed (as opposed to whenever it is of use to the client, as with a delegated targets role).  The reference implementation may be instructive here.

It should be said, though, that the distinction between roles and delegations has confused developers of TUF implementations.  The reference implementation itself has occasionally missed important subtleties.

#### Code Reuse for Director & Image Repo:
The reference implementation is able to employ TUF code that does not have any concept of Director vs Image Repository to do most of the work.  The bits in the Uptane implementation that do distinguish between the types of repositories are pretty short.  It's possible that the enforced reliance on the TUF reference implementation in the Uptane reference implementation means that we haven't had to struggle with where to put boundaries in the way other Uptane implementers might have to, so feedback about this from developers would be very welcome.  (If there's a pain point, maybe that recommends a deployment guideline.)  **Because of this, I don't think it makes sense to give the Director's roles and Image Repo's roles different names, or anything like that.  Note that the algorithms are largely the same.**  It can (and probably should) be almost entirely the same code handling them.  The two repository types have only a few distinctions.

#### Code Reuse for Signing and Signature Verification
As for signing code, I don't think there's much difficulty in producing modular and readable signing code for all roles, but I'm not sure that's something Patrick was commenting on.  (Please correct me if I'm wrong!)

#### Code Reuse for Root and Targets, and for Timestamp and Snapshot
There are places where it can be tempting to write separate code for each role, but modularity is an important goal.  To the extent possible, for example, I think it is wise to treat Root's delegations similarly to targets roles' delegations, even though the latter have a good bit more functionality.  If there are lessons and feedback here, that's probably a good subject for the deployment considerations, too.

**Comment by jhdalek55** [comment]
So, do we have to add/delete/change anything in the Standards beyond the revised definitions Marina suggested? And, should we develop something on this topic for the deployment pages?

**Comment by patrickvacek** [comment]
> The reference implementation is able to employ TUF code that does not have any concept of Director vs Image Repository to do most of the work.

Same with our implementation. I think this is a benefit: we can reuse a lot of logic and use the TUF spec as a guide for how these roles should work at a basic level.

> As for signing code, I don't think there's much difficulty in producing modular and readable signing code for all roles, but I'm not sure that's something Patrick was commenting on.

For whatever reason, it wasn't immediately obvious to me that I could reuse logic in the Root and and Targets roles for key management. I figured it out quickly enough, but it was a bit of a challenge to get it working correctly for both with maximum code reuse, as there are some slight differences.

It sounds like what I'm talking about are mostly deployment considerations, but if I find a place in the spec that could be improved or clarified, I'll bring it up.

**Comment by jhdalek55** [comment]
Patrick, could you make a note of where the issues discussed in this thread
should be addressed in the Deployment pages? Would it fit under one of the
designated headings, or do we need to create a new page for these concerns?

If you have a chance to think about the above in the next few days, let me
know. I am going to be circulating a list of the topics on the Deployment
page to see if we can solicit volunteers to help in filling in content in
this section and I'd like the list to be as complete as possible.

Lois

**Comment by patrickvacek** [comment]
> Patrick, could you make a note of where the issues discussed in this thread should be addressed in the Deployment pages? Would it fit under one of the designated headings, or do we need to create a new page for these concerns?

I think most of the interesting parts would be in the `deployment/key_management.md` page, assuming that I understand correctly that both server-side and client-side implementation will be discussed there. Possibly there could be some places in `deployment/normal_operation.md` that could talk about code reuse (like the text that Sebastien wrote a few comments up), perhaps such as the  `What can an Uptane-compliant system look like?` section.

**Comment by JustinCappos** [comment]
@mnm678 would also be a good person to have a look once we get the deployment doc into a format that is easier to collaboratively edit.  She made the changes to the other docs to get them in line...
