### ISSUE TITLE
Gateways and primary/secondary communications

### ISSUE THREAD

**Issue by sam-m-weber** [uptane/uptane-standard#50]
The spec assumes that the primary is able to communicate directly with all of the secondaries.  Is this realistic?  Even if one assumes that gateways will forward communications to/from the primary and secondaries on another network, Uptane will have to be aware of this because the gateways themselves might be updated -- flashing new firmware onto a gateway while it is in the middle of forwarding updates to other ECUs would not be good.

**Comment by JustinCappos** [comment]
I read through the spec and do not see where it says the primaries and secondaries directly communicate.  It says multiple places that the secondary and primary transmit information but nowhere does it say that they must be on the same network or that an intermediary cannot forward traffic.  Similarly, the document repeatedly talks about primary to director communications, but of course this will go over a variety of networking hardware which isn't said.  I'm not sure why the primary <-> secondary communication needs more discussion than other links.

If the consensus is that it's worth adding an explicit mention of the fact one should not flash a gateway that is being actively used by something mission critical, I don't oppose adding it to the deployment considerations.  My initial impression is this is perhaps a little bit too pedantic.  (E.g., We also don't say that you shouldn't update a safety critical component in an unsafe way while the car is moving...)

**Comment by sam-m-weber** [comment]
The fact that it isn't addressed is the issue.  The protocol described in "Installing images on ECUs" can't be followed as-written if the ECU is a gateway, which means that each implementer will have to come up with their own way of dealing with the situation.  Personally, I can think of a number of ways of doing this, but who knows what a particular implementer will do and therefore what security or reliability issues will result from their choices. Also, in general, I don't think it is a good idea to have an algorithm which can't be followed as-written.

**Comment by iramcdonald** [comment]
Hi,

Without describing details, I note that this issue (i.e., updating gateways
is fundamentally
different than updating endpoint Secondaries) was raised a long time ago in
my work on
FOTA requirements at a large OEM and we wound up explicitly treating this
topic.

We also wound up acknowledging that because of evolution over model years,
even when
a central FOTA mechanism like Uptane was deployed, for some years it will
have to co-exist
w/ what we called "Self-Updaters" (obvious ones are Head Units and
Telematics ECUs, both
of which tend to get FOTA deployed some model years ahead of other ECUs in
the vehicle).

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by JustinCappos** [comment]
I added text to the deployment considerations in E.3 addressing this.
