### ISSUE TITLE
Time server response

### ISSUE THREAD

**Issue by sam-m-weber** [uptane/uptane-standard#52]
In the Time Server section, it says that "it SHALL sign each token together with the current time," which seems to say that if n tokens are sent to it, the server will send back n signed objects: token 1 together with the time, token 2 with the time, etc.  I presume that the server will actually combine the time with the list of tokens and do one signature operation on the combination.  Could this be either corrected or made clearer that this is actually what is meant?

(I had previously put this in with a number of small clarification requests, but Justin requested I raise it separately.)

**Comment by JustinCappos** [comment]
Should be easy to clarify.  Perhaps just "In response, it SHALL sign each token together with the current time." -> "In response, it SHALL return a signed response that covers each token and the current time.  This may be done in a variety of ways, including in a single message covering all tokens or as a separate signed response for each token."

**Comment by iramcdonald** [comment]
Hi,

It's a Secondary (not the Primary) that created each token.  A Secondary
shouldn't
have to parse a signed list of returned tokens to find the relevant one.

If we have signed time tokens (and I always liked this feature), then they
really should
be individually signed, so that the Primary can break them out and pass
each signed
time token to the appropriate Secondary.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by jhdalek55** [comment]
Would PR#57 need some modification in response to Ira's concern?

Lois

**Comment by awwad** [comment]
https://github.com/uptane/uptane-standard/pull/57#pullrequestreview-206345249
