### ISSUE TITLE
Normative out-references to TUF

### ISSUE THREAD

**Issue by sam-m-weber** [uptane/uptane-standard#56]
As a process concern, at a number of places the specification says things like "A primary ECU SHALL download metadata and images following the rules specified in {{TAP-5}}".  Would this cause problems with the IEEE, since it would allow changes to be made to the specification by the maintainers of TUF, outside of the IEEE process?

**Comment by iramcdonald** [comment]
Hi,

I disagree with Justin about this issue (normative out-references to TAP-5).

I strongly feel that *all* out-references to TAP-n should be changed in the
IEEE-ISTO Uptane Alliance standard to SHOULD (Recommendation).

I think that automotive OEMs would dislike the current normative out-refs
and I'm sure that SAE vehicle security committees would dislike them.

Speaking from 25 years experience writing international standards in
IETF, IEEE, DMTF, SAE, TCG, and Linux Foundation, a *standard*
should be entirely self-contained.  It especially should NOT have any
open-ended out-references (as these to TAP-5 are).  It's acceptable
and reasonable to have an out-reference to ONE specific requirement
from another standard.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by JustinCappos** [comment]
I'd favor moving the duplicating the content and adding it into the spec,
rather than externalizing it in this case.  These are not optional features
that should be considered, but are key to the security guarantees of Uptane.

**Comment by jhdalek55** [comment]
If this is a matter of importing something directly from the TAP 5 into the document, I could probably take care of it, as long as I'm directed where to get it from and exactly where it belongs.

**Comment by trishankatdatadog** [comment]
I think TAP 5 is unnecessary for Uptane, and vote against any mention or import of it. I am open to being proven wrong.

**Comment by mnm678** [comment]
TAP 5 is mentioned in #root_meta (quoted above). It looks like there are references to TAPs 3, 4, and 5 at various places in the current document. 

The text of these TAPs are rather long (for example [tap 5](https://github.com/theupdateframework/taps/blob/01726d203c9b9c029d26f6612069ce3180500d9a/tap5.md#downloading-metadata-and-target-files)). Is there a way to only include the critical information from the TAPs?

**Comment by jhdalek55** [comment]
I would think we only need whatever specific sentences in the TAP that 
explain how the influence the process in question. I don't think we 
would want to use the entire TAP.


Lois

On Mon, Feb 25, 2019 at 07:35 PM, mnm678 wrote:

TAP 5 is mentioned in #root_meta (quoted above). It looks like there are 
references to TAPs 3, 4, and 5 at various places in the current 
document.

The text of these TAPs are rather long (for example tap 5 
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_theupdateframework_taps_blob_01726d203c9b9c029d26f6612069ce3180500d9a_tap5.md-23downloading-2Dmetadata-2Dand-2Dtarget-2Dfiles&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hgBKIqNYIOwzXeBjPUaKRw&m=hwP31bkUn9Jc59ksRcS1op0MtMskfLnqQzQDETiF48A&s=eDDbMEYyEWkYsPn2mAFO_bIfPNw4KC5Ynq2kLWJSj4o&e=> 
). Is there a way to only include the critical information from the 
TAPs?


—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub 
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_uptane_uptane-2Dstandard_issues_56-23issuecomment-2D467242919&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hgBKIqNYIOwzXeBjPUaKRw&m=hwP31bkUn9Jc59ksRcS1op0MtMskfLnqQzQDETiF48A&s=SD0ePRGkpRiAcX9_22rw8dqx-CrJYYR1YTrsiRqQ4LE&e=> 
, or mute the thread 
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AN5qX9Ksnaem65Am0tyxnsFAm1uu7Fxlks5vRIFtgaJpZM4bFTwg&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hgBKIqNYIOwzXeBjPUaKRw&m=hwP31bkUn9Jc59ksRcS1op0MtMskfLnqQzQDETiF48A&s=eHb3pVFJs_4hstjI3XzcqQT7SFTaa07dhpQUbNs2pis&e=> 
.

**Comment by awwad** [comment]
We don't refer to the TUF specification in the standard (with one exception in 5.2.7), so it seems likewise unnecessary to refer to the TAPs in the standard.  It stands to reason that we'd integrate only any necessary language from TAPs into the Uptane standard, the same way that we've integrated the necessary elements of the TUF specification (which is most of them).  In the case of TAP 5, I think most of the content isn't needed, yes.

Consider for example the current text of Uptane standard section 5.2.4:
```The Snapshot metadata MAY also list the root metadata filename and version number. This is no longer required because of the implementation of [TAP-5], but MAY be included for backwards compatibility.```

I'd argue that it's not required to refer to TAP 5 there; it's only necessary to explain that root-in-snapshot (pre-TAP5) is OK.  (As a sidenote, I'm not sure that's really something we need to advise, but that's a tangent.)

**Comment by JustinCappos** [comment]
Thanks for raising this.  Let's discuss the value (or lack of value) of
this during the workshop.  It would be better to decide with automaker
feedback.

**Comment by JustinCappos** [comment]
We resolved to link to specific version numbers of the TUF spec / TAPs (at a minimum).  I'll push for us to link and refer to the head of the branch containing that version so it is completely clear.

@jhdalek55 Can you help to resolve this?

**Comment by jhdalek55** [comment]
I think I can do this. I'll give it a go on Monday. Glad the meeting provided some answers to so many of these open issues.

**Comment by JustinCappos** [comment]
> I think TAP 5 is unnecessary for Uptane, and vote against any mention or import of it. I am open to being proven wrong.

FYI: the resolution was that implementers MAY support TAP 5.  #70 is the proposed fix for this.  Review kindly requested.

**Comment by JustinCappos** [comment]
#70 was merged, but the broader normative out-reference issue still remains.  @jhdalek55 is working on this.s

**Comment by jhdalek55** [comment]
Honestly, I may need some guidance on this. I understand what needs to be done and initially I thought I could figure this out. But, my git hub skills are not very advanced and I think I need also some clarification as to what within TAP 5 I'm linking to. I'm still willing to try to fix it this, as I want to be able to do in future iterations, but I think I will need some help.

**Comment by awwad** [comment]
Poke me whenever. :)

**Comment by jhdalek55** [comment]
Thanks. Maybe we can look at this tomorrow.

**Comment by tkfu** [comment]
I'd just like to point out that, since the beginning, I've been referencing specific commits in all normative references. As long as SHA-1 isn't broken, those normative references cannot be changed. And given that they reference an open-source git repo, I think it's reasonable to assume that they are durable, even if the github links eventually rot.

**Comment by iramcdonald** [comment]
Hi Jon,

Um.  SHA-1 was rather famously broken by Google in February 2017:

https://security.googleblog.com/2017/02/announcing-first-sha1-collision.html

SHA-1 has long been deprecated by IETF and US NIST standards.  The use of
SHA-1 is now prohibited in any future or updated IETF protocol.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by tkfu** [comment]
If we were talking about relying on it for security properties, I would be worried...but I think it’s still secure enough to identify a particular and stable version of a text. Perhaps I should have said, “as long as a person with commit rights to an authoritative source for the TUF git repositories doesn’t find a SHA-1 collision, then rewrite the history of the repo without causing anyone to notice, and successfully promulgate their new git repo across the entire internet, these normative references can not be changed.” But I thought that was a little less punchy.

**Comment by jhdalek55** [comment]
So, just to clarify, do we need additional copy along with the appropriate reference link?
