### ISSUE TITLE
Move time server designs to deployment considerations...

### ISSUE THREAD

**Issue by JustinCappos** [uptane/uptane-standard#66]
As was resolved in the Uptane workshop today, we will move the time server mechanisms to the deployment considerations.  The spec will instead state why a notion of wall clock time is important for checking expiry of certificates and point to the deployment considerations for options.

@awwad, Would you kindly take a first crack at this?  Please remember to leave a place for Ira to add text about the secure time options he is aware of.

**Comment by tkfu** [comment]
On the 03/13 standards call, we noted that this overlaps with #31, which @awwad is working on.

**Comment by jhdalek55** [comment]
On the 3/27 standards call, it was noted that this is connected to PR#31 which is being worked on by  @awwad .

**Comment by jhdalek55** [comment]
Question--Since issue #31  has now been addressed and closed, is there any need to keep this open?

**Comment by awwad** [comment]
I think this is a separate issue:
I think the intention here was to extract all the timeserver material from the Standard and move it into the deployment considerations, making sure to leave only minimal requirements about assuring trustworthy time, probably pointing to the section of the deployment considerations that includes it.  Unless that has changed, I think this issue should probably remain open.

It might make more sense to do this once the deployment considerations are in a git repository.

**Comment by jhdalek55** [comment]
Ok. But, perhaps then the intentions of this issue need to be reframed. 
Maybe even just mark it for now as "Leave open pending establishment of 
deployment markdown files."


I think it could be helpful if someone in the group could begin to 
earmark what material should be removed from the Standard.


Thanks for the clarification.


Lois

On Tue, Apr 02, 2019 at 12:58 PM, Sebastien Awwad wrote:

I think this is a separate issue:

I think the intention here was to extract all the timeserver material 
from the Standard and move it into the deployment considerations, making 
sure to leave only minimal requirements about assuring trustworthy time, 
probably pointing to the section of the deployment considerations that 
includes it.  Unless that has changed, I think this issue should 
probably remain open.

It might make more sense to do this once the deployment considerations 
are in a git repository.


—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub 
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_uptane_uptane-2Dstandard_issues_66-23issuecomment-2D479094325&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hgBKIqNYIOwzXeBjPUaKRw&m=hJhOUpaW69eygMFiTrFsU7TBZ_KE3rxKvOy79luEpu0&s=Ecx5fycRTx9Yb0Los1Tl1bdOYrIHYRPnM6FRy7glx9g&e=> 
, or mute the thread 
<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_notifications_unsubscribe-2Dauth_AN5qX6k6qMdKs1-2D5lmxLcg0hWD178FRIks5vc4xGgaJpZM4baCg4&d=DwMFaQ&c=slrrB7dE8n7gBJbeO0g-IQ&r=hgBKIqNYIOwzXeBjPUaKRw&m=hJhOUpaW69eygMFiTrFsU7TBZ_KE3rxKvOy79luEpu0&s=jNmA0hEQPwMfg4ydXMd-mOzd_6gPQEei7YvLII3voQU&e=> 
.

**Comment by jhdalek55** [comment]
On the 4/10 Standards call, it was agreed to close this issue and open an issue noting the work is ongoing on the Uptane web site.

**Comment by jhdalek55** [comment]
On the 4/10 Standards call, @tkfu  agreed to submit a pull request to close out this issue.

**Comment by jhdalek55** [comment]
On the 4/24 Standards call, @tkfu agreed to complete work on this issue. See PR #104.

**Comment by jhdalek55** [comment]
Can we get a review on the PR cited above?

**Comment by jhdalek55** [comment]
Unrelated to the review of this pull request, I am transferring the last of the Deployment files to the setting up repositories page. There seems to be quite a bit in this section about the Time server. Should I bring in everything from the deployment document that mentions the Timeserver? And if there are pieces of the existing standard that plan to be brought in, if someone could suggest what page they should be on, I could move them as well.

**Comment by jhdalek55** [comment]
On the 5/8 Standards call, @JustinCappos  agreed to review PR #104 which would close out this issue.
