### ISSUE TITLE
Custom metadata in multi-role delegations

### ISSUE THREAD

**Issue by tkfu** [uptane/uptane-standard#79]
In a multi-role delegation, we must verify that the **non-custom** metadata from each role (or rather, from a sufficient threshold of roles) matches. However, we don't say what to do if **custom** metadata does not match. I'm going to spitball a bunch of ideas, here. We could:

* Return all of the different custom metadata along with information about which role it came from, and leave it to the implementation to sort out what to do
* Check if it is possible to merge the non-matching custom metadata without conflict, and return that if there is / return an error if there's a merge conflict
* Return only the intersection of the set
* Disallow custom metadata in multi-role delegations altogether
* Mandate that all metadata, including custom metadata, must match
* Split custom metadata into demarcated "MUST match" and "MAY match" sub-sections, then leave it up to the implementation to decide what to do with the "MAY match" metadata

Option 1 is a bit unsatisfactory, but given that it is custom metadata, with all of the implementation freedom that implies, it might be the most reasonable solution.

Option 2 seems nice, but would add annoying complexity, and opens up a large can of worms about what merging logic to implement.

Option 3 seems safer that option 2, but has most of the same problems.

Option 4 doesn't feel plausible; custom metadata is almost always useful.

Option 5 might be too restrictive.

Option 6 is a fairly big change that would have to propagate out throughout the standard, and also just feels a bit messy.

Thoughts? Other solutions?

**Comment by trishankatdatadog** [comment]
I propose updating [this rule](https://github.com/uptane/uptane-standard/pull/75/files#diff-aaf9170627e7d94a7c20fa9ef96f3ae1R938) to say:

>Locate all sets of roles which have agreeing (i.e. identical) non-custom **and custom** metadata...

**Comment by awwad** [comment]
It is worth considering whether the policy toward custom metadata matching should differ between multi-repository (TAP 4 -- e.g. Director + Image Repo) and multi-role (TAP 3) delegations.  Having a different policy toward custom metadata with the two types might be confusing.

Note that the standard currently says that ECU ID (Director only), hardware ID (generally all repos), and release counter (generally all repos) are custom metadata.

Note also that Uptane uses multi-repository (TAP 4) delegation/mapping in the mapping file that specifies Director and Image Repository and requires that they agree on (only) non-custom metadata.  It cannot require agreement on custom metadata, because ECU ID is custom metadata that is only reasonably possible to provide in Director (and not Image Repository) metadata.

The reference implementation currently employs strategy 1 (return all) for multi-repository (TAP 4) and does something different for multi-role (TAP 3): it returns the highest-priority role's target info (including custom) if the non-custom metadata all matches otherwise in a multi-role delegation.

**Comment by iramcdonald** [comment]
Hi Jon,

[hopefully this reply isn't just noise]

In the IETF and IEEE-ISTO PWG Internet Printing Protocol (IPP), we have
long had a Client request feature for the "MUST match" attributes and
values.
The required Printer behavior is that, if any "MUST match" fails, then the
Job
MUST be aborted and detailed errors returned to the Client.

As custom metadata attributes are likely to proliferate over time, this
might be
the best long-term approach for Uptane as well.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by tkfu** [comment]
On the 03/13 standards call, @JustinCappos pointed out that this issue affects TUF more broadly, and suggested that we bring the discussion to the wider community. @tkfu will open an issue in the main TUF repository.

**Comment by jhdalek55** [comment]
According to my notes from the 3/27 call, there was no resolution on this. If this is being addressed by TUF, do we need to keep this open?

**Comment by tkfu** [comment]
We should leave this open, at least until there's a resolution upstream. I'll link an upstream issue soon.

**Comment by tkfu** [comment]
Closed by #98.
