### ISSUE TITLE
Snapshot contents inconsistency

### ISSUE THREAD

**Issue by patrickvacek** [uptane/uptane-standard#90]
The standard is inconsistent about what it claims are the required contents of the Snapshot metadata. This may be related to differences between the 0.9 and 1.0 TUF spec versions.

[Section 5.2.4. of the Uptane spec (Snapshot Metadata)](https://uptane.github.io/uptane-standard/uptane-standard.html#snapshot_meta) says "The Snapshot metadata lists version numbers and filenames of all Targets metadata files." and "the Snapshot metadata SHALL contain the following information: The filename and version number of the each Targets metadata file on the repository". There is no mention of hashes or lengths. This matches [TUF spec version 1.0 section 4.4. (File formats: snapshot.json)](https://github.com/theupdateframework/specification/blob/master/tuf-spec.md#4-document-formats), which says "It lists the version numbers of all metadata on the repository [...]".

[Section 5.1.3. of the Uptane spec (The Snapshot role)](https://uptane.github.io/uptane-standard/uptane-standard.html#snapshot_role) says "A repository’s Snapshot role SHALL produce and sign metadata about all Targets metadata the repository releases, including the current version number and hash of the top-level Targets metadata, and the version numbers and hashes of all delegated targets metadata, as described in Section 5.2.4." This is similar to [TUF spec version 0.9 section 4.4. (File formats: snapshot.json)](https://github.com/theupdateframework/specification/blob/master/tuf-spec.0.9.txt), which says "It lists hashes and sizes of all metadata on the repository [...]". However, that is the only place I've found were lengths or sizes are stipulated.

[Section 5.4.4.6. of the Uptane spec (How to check Targets metadata)](https://uptane.github.io/uptane-standard/uptane-standard.html#check_targets) item 2 says "The hashes (if any), and version number of the new Targets metadata file MUST match the latest Snapshot metadata." This implies that hashes are optional. (Version checking is also mentioned in the preceding section.)

So which is it? Are hashes of Targets metadata required, optional, or discouraged in Snapshot metadata? Are lengths undesirable? I don't know the history of the TUF spec, and the git log does not help, as the quoted text has been unchanged since the introduction of both files in
the second commit in 2017. Why that was changed between TUF spec versions? (And why they are two versions of that spec in that repo, anyway?)

As far as I understand, there is no harm in checking lengths and hashes, and the length has an explicit benefit: it will prevent you from downloading more bytes than necessary in case something went wrong. But whatever the consensus is, we should be consistent.

**Comment by trishankatdatadog** [comment]
Hi @patrickvacek, yes, I can see why this is confusing. Most of these changes came from [Mercury](https://www.usenix.org/conference/atc17/technical-sessions/presentation/kuppusamy).

The TLDR is that for most use cases, only the filenames and corresponding version numbers of all targets metadata files are necessary.

It used to be that TUF had hashes and file sizes instead, but this had two drawbacks: (1) unnecessary bandwidth, and (2) no prevention of rollback attacks against targets not yet downloaded.

Adding hashes (and possibly file sizes( are important for another use case (see Section 5.6 of the Mercury paper) that should not be relevant to the vast majority of Uptane deployments. As such, as I think we can remove their mention altogether.

@JustinCappos what do you think?

**Comment by JustinCappos** [comment]
Yes, I agree with Trishank's assessment and call for action.  There is a
very narrow case where hashes have an advantage over version numbers, but
versions are far superior overall in security and file size.

**Comment by patrickvacek** [comment]
Thanks for the explanations. I reviewed the Mercury paper again and now I have a better understanding of the intentions. I agree that if hashes in snapshot.json are removed, we should mention it in the threat model. Alternatively we could list hashes as a "MAY include" instead of the current language, but that is probably more confusing for little benefit.

There is one other aspect that I think merits an explanation if we don't require hashes: how to actually recover if the snapshot role is compromised. According to Mercury section 5.3, "Administrators must use  an offline backup to restore all project metadata and packages to a verifiable point before the compromise." The Uptane standard currently makes no mention of offline backups, let alone as a necessary step for recovering from compromise.

**Comment by iramcdonald** [comment]
Hi Patrick et al,

Offline backups is a large, complex area that probably should be
out-of-scope to Uptane Standard (or Deployment Considerations).

Recovery from offline backups *always* requires the intervention
of one or more human administrators (otherwise, they're not really
"offline" backups).

In a OTA systems architecture team that I was part of in the past, the
Primary was responsible for independently (of the Director or other
backend roles), having collected the manifest of all updatable ECUs,
either retrieving from the ECUs or retrieving from Image Repository
(or CDN servers) valid copies of all the current installed images
*before* starting the distribution and installation process on Target
ECUs - so that successful fallback from installation failures was
guaranteed.  I suspect that's a common approach for OEMs using
whatever OTA framework.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by trishankatdatadog** [comment]
I concur with @iramcdonald

**Comment by patrickvacek** [comment]
> Offline backups is a large, complex area that probably should be out-of-scope to Uptane Standard (or Deployment Considerations).

Fair enough. I'd overlooked that the old Deployment Considerations do actually mention this explicitly in [section A.3](https://docs.google.com/document/d/17wOs-T7mugwte5_Dt-KLGMsp-3_yAARejpFmrAMefSE/edit#heading=h.h65c8rsw9cfw).

**Comment by patrickvacek** [comment]
I made a PR to address these issues (https://github.com/uptane/uptane-standard/pull/92) but I still have a question about lengths. (See the PR for details.)
