### ISSUE TITLE
An update check should not necessarily require sending a full vehicle version manifest

### ISSUE THREAD

**Issue by tkfu** [uptane/uptane-standard#94]
In a vehicle with a lot of secondary ECUs, a vehicle version manifest can get very large very fast, especially if there is a lot of custom metadata. I'd like to make it optional to send a manifest as the first step in checking for an update. Instead, sending the manifest would only be a MUST when it changes.

In the common case, where there's no update, this would allow clients to check for an update simply by downloading the current timestamp metadata, a much smaller file. It's backwards-compatible with any existing implementation, because the client can still send the manifest as often as it wants to.

**Comment by iramcdonald** [comment]
Hi,

In a past life, working with an OEM Systems Architecture team looking
at deployment of Uptane OTA, there was strong consensus that the
initial step of Manifest from vehicle before a Primary requests updates
from a Director had to be a MUST.

I would suggest Uptane keep the requirement for the Manifest (because
backend Vehicle Inventory databases could have defects), but support
for Custom Metadata in the Manifest ought to be a SHOULD.

Even for core metadata, if we know Target ECU's Hardware ID. Device ID,
and Firmware Version that's sufficient for safe updates.  Such things as
the ECU's installed library synopsis is nice to have, but not very important
(because that should certainly be known in the OEM's Image Repository).

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by JustinCappos** [comment]
There isn't a requirement to send a complete manifest, right?  An ECU could
always just send a diff.  Each ECU does need to send *something* though, if
only to say that nothing changed for that ECU.

Justin

**Comment by awwad** [comment]
Just my $0.02, subject to inflation:
Timing and completeness of ECU manifests sounds less security-critical and more implementation-specific, which is why I've personally always thought of when they get sent as out of scope for Uptane, so long as _it happens sometimes_.  A Director can always make judgment calls about what it wants to see before it issues new metadata for a vehicle.

**Comment by iramcdonald** [comment]
Hi,

Let me expand a bit here on rationale for a mandatory Manifest.

The OEM System Architecture team I collaborated with pointed out that
an ECU could be replaced or updated by an aftermarket shop without
the knowledge of the OEM backend.  The requirement for a full Manifest
was to allow re-sync of the backend Vehicle Inventory DB.

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by iramcdonald** [comment]
Hi Patrick,

I'm probably being naive here.

How would a *vehicle* know a priori that the OEM backend Vehicle Inventory
DB
was out-of-date?  The Uptane Primary wouldn't know if a service tool
(dealer or
independent) had reported/negotiated a firmware update with the OEM backend.

Also, if a Manifest is entirely left out in some circumstances, then there
are two
downsides:

(1) OEM Director logic has to change to start updating a vehicle w/out a
Manifest
trigger (how does it know when to do so and if the vehicle can be
contacted?).

(2) Vehicle ECUs can't send a time token to the Director in the missing
Manifest, so
the possible signing of a time token feature can't be implemented.

The OEM System Architecture team I collaborated with was adamant that the
only
way a FOTA update cycle would ever start was based on trigger from the
vehicle
of a fresh Manifest (i.e., they were strongly opposed to the asynchronous
"push"
of updates from Director).

Cheers,
- Ira

Ira McDonald (Musician / Software Architect)
Co-Chair - TCG Trusted Mobility Solutions WG
Co-Chair - TCG Metadata Access Protocol SG
Chair - Linux Foundation Open Printing WG
Secretary - IEEE-ISTO Printer Working Group
Co-Chair - IEEE-ISTO PWG Internet Printing Protocol WG
IETF Designated Expert - IPP & Printer MIB
Blue Roof Music / High North Inc
http://sites.google.com/site/blueroofmusic
http://sites.google.com/site/highnorthinc
mailto: blueroofmusic@gmail.com
PO Box 221  Grand Marais, MI 49839  906-494-2434

**Comment by jhdalek55** [comment]
On the 4/10 Standards call, it was noted that after some discussion on the issue page a consensus has been reached. @tkfu will submit a PR to add the needed language.

**Comment by jhdalek55** [comment]
On the 4/24 Standards call, @tkfu agreed to complete the work needed to close out this issue.

**Comment by jhdalek55** [comment]
On the 5/8 Standards call, @patrickvacek noted that he believed this was still on @tkfu TODO list and that he will follow up with @tkfu .
